hl.on("hyprland.start", function()
	hl.exec_cmd("waybar &")
	hl.exec_cmd("awww-daemon &")
	hl.exec_cmd("hypridle &")
	hl.exec_cmd("swaync &")
	hl.exec_cmd("hyprlock")
	hl.exec_cmd("~/.config/hypr/scripts/wallpaperrotate.sh &")
end)
