-- Generated by hyprconf2lua v1.3.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives
---@module 'hl'
--##################
--## MY PROGRAMS ###
--##################
-- See https://wiki.hypr.land/Configuring/Keywords/
-- Set programs that you use
local terminal = "kitty"
local fileManager = "setsid thunar >/dev/null 2>&1"
local menu = "rofi -show drun"
local browser = "google-chrome-stable --ozone-platform=x11"
local lock = "hyprlock"
--#### $chatGPT = google-chrome-stable --new-window https://chat.openai.com
local chatGPT = "google-chrome-stable --app=https://chatgpt.com"
local power = "cd /home/hondo/tvcontrol/ && . /power.sh"
local hdmi = "cd /home/hondo/tvcontrol/ && . /hdmi.sh"
--##################
--## KEYBINDINGS ###
--##################
-- See https://wiki.hypr.land/Configuring/Keywords/
local mainMod = "SUPER"
-- Sets "Windows" key as main modifier
-- Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
hl.bind(mainMod .. " + " .. "Return", hl.dsp.exec_cmd("kitty"))
-- Opens kitty terminal
hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())
-- Closes selected window
hl.bind(
	mainMod .. " + " .. "M",
	hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit")
)
hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("setsid thunar >/dev/null 2>&1"))
hl.bind(mainMod .. " + " .. "W", hl.dsp.exec_cmd("google-chrome-stable --ozone-platform=x11"))
hl.bind(mainMod .. " + " .. "V", hl.dsp.window.float())
hl.bind(mainMod .. " + " .. "L", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + " .. "R", hl.dsp.exec_cmd("rofi -show drun"))
hl.bind(mainMod .. " + " .. "P", hl.dsp.exec_cmd("cd /home/hondo/tvcontrol/ && . /power.sh"))
-- Turn on Power to Samsung TV
hl.bind(mainMod .. " + " .. "H", hl.dsp.exec_cmd("cd /home/hondo/tvcontrol/ && . /hdmi.sh"))
-- Toggle HDMI inputs to Samsung TV
hl.bind(mainMod .. " + " .. "I", hl.dsp.exec_cmd("~/.config/hypr/scripts/wallpaper-selector.sh"))
hl.bind(mainMod .. " + " .. "J", hl.dsp.layout("togglesplit"))
-- dwindle
hl.bind(mainMod .. " + " .. "C", hl.dsp.exec_cmd("google-chrome-stable --app=https://chatgpt.com"))
hl.bind(mainMod .. " + " .. "N", hl.dsp.exec_cmd("~/.config/rofi/scripts/nordvpn-menu.sh"))
hl.bind(mainMod .. " + " .. "right", hl.dsp.window.move({ monitor = "-1" }))
hl.bind(mainMod .. " + " .. "left", hl.dsp.window.move({ monitor = "+1" }))
hl.bind(mainMod .. " + " .. "Minus", hl.dsp.exec_cmd("~/.config/hypr/scripts/zoom.sh decrease 0.3"))
--Zoom Out
hl.bind(mainMod .. " + " .. "Equal", hl.dsp.exec_cmd("~/.config/hypr/scripts/zoom.sh increase 0.3"))
--Zoom In
hl.bind(mainMod .. " + " .. "SHIFT+PRINT", hl.dsp.exec_cmd("hyprshot -m region"))
--Screen Capture -region of screen hyprshot
hl.bind(mainMod .. " + " .. "PRINT", hl.dsp.exec_cmd("hyprshot -m window"))
--screen Capture - entire window hpyrshot
-- Move focus with mainMod + arrow keys
-- bind = $mainMod, left, movefocus, l
-- bind = $mainMod, right, movefocus, r
-- bind = $mainMod, up, movefocus, u
-- bind = $mainMod, down, movefocus, d
-- Switch workspaces with mainMod + [0-9]
hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = "1" }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = "2" }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = "3" }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = "4" }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = "5" }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = "6" }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = "7" }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = "8" }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = "9" }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = "10" }))
-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))
-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "+1" }))
hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "-1" }))
-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })
-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true })
-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
hl.bind(mainMod .. " + " .. "slash", hl.dsp.exec_cmd("kitty -e nvim ~/.config/hypr/modules/keybinds.lua"))
